<?xml version="1.0" encoding="utf-8"?><Database Name="NCKH" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-K74B5AQN\SQLEXPRESS;Initial Catalog=NCKH;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NCKHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BienBan" Member="BienBans">
    <Type Name="BienBan">
      <Column Name="MaBienBan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaGV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDuGio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongDiem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SiSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DuGio_BienBan" Member="DuGio" ThisKey="MaDuGio" OtherKey="MaDuGio" Type="DuGio" IsForeignKey="true" />
      <Association Name="GiangVien_BienBan" Member="GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TieuChi" Member="TieuChis">
    <Type Name="TieuChi">
      <Column Name="MaTC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTieuChi" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TieuChi_CTDanhGia" Member="CTDanhGias" ThisKey="MaTC" OtherKey="MaTC" Type="CTDanhGia" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="MaCV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ChucVu_GiangVien" Member="GiangViens" ThisKey="MaCV" OtherKey="MaCV" Type="GiangVien" />
    </Type>
  </Table>
  <Table Name="dbo.ChuongTrinh" Member="ChuongTrinhs">
    <Type Name="ChuongTrinh">
      <Column Name="MaCT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ChuongTrinh_GiangVien" Member="GiangViens" ThisKey="MaCT" OtherKey="MaCT" Type="GiangVien" />
    </Type>
  </Table>
  <Table Name="dbo.CT_ThongBao" Member="CT_ThongBaos">
    <Type Name="CT_ThongBao">
      <Column Name="MaTB" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NguoiNhan" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TrangThaiDoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ThongBao_CT_ThongBao" Member="ThongBao" ThisKey="MaTB" OtherKey="MaTB" Type="ThongBao" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTDanhGia" Member="CTDanhGias">
    <Type Name="CTDanhGia">
      <Column Name="MaPhieuCham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TieuChi_CTDanhGia" Member="TieuChi" ThisKey="MaTC" OtherKey="MaTC" Type="TieuChi" IsForeignKey="true" />
      <Association Name="PhieuCham_CTDanhGia" Member="PhieuCham" ThisKey="MaPhieuCham" OtherKey="MaPhieuCham" Type="PhieuCham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTNhanXet" Member="CTNhanXets">
    <Type Name="CTNhanXet">
      <Column Name="MaNX" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPhieuCham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="NhanXet_CTNhanXet" Member="NhanXet" ThisKey="MaNX" OtherKey="MaNX" Type="NhanXet" IsForeignKey="true" />
      <Association Name="PhieuCham_CTNhanXet" Member="PhieuCham" ThisKey="MaPhieuCham" OtherKey="MaPhieuCham" Type="PhieuCham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangKyThaoGiang" Member="DangKyThaoGiangs">
    <Type Name="DangKyThaoGiang">
      <Column Name="MaDK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaGV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TietBD" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NgayThaoGiang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NhomHoc" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenBaiHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="DangKyThaoGiang_DuGio" Member="DuGios" ThisKey="MaDK" OtherKey="MaDK" Type="DuGio" />
      <Association Name="DangKyThaoGiang_ThongBao" Member="ThongBaos" ThisKey="MaDK" OtherKey="MaDK" Type="ThongBao" />
      <Association Name="GiangVien_DangKyThaoGiang" Member="GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="HocKy_DangKyThaoGiang" Member="HocKy" ThisKey="MaHK" OtherKey="MaHK" Type="HocKy" IsForeignKey="true" />
      <Association Name="NamHoc_DangKyThaoGiang" Member="NamHoc" ThisKey="MaNH" OtherKey="MaNH" Type="NamHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DuGio" Member="DuGios">
    <Type Name="DuGio">
      <Column Name="MaDuGio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GVDuGio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThuKy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DuGio_BienBan" Member="BienBans" ThisKey="MaDuGio" OtherKey="MaDuGio" Type="BienBan" />
      <Association Name="DuGio_PhieuCham" Member="PhieuChams" ThisKey="MaDuGio" OtherKey="MaDuGio" Type="PhieuCham" />
      <Association Name="DangKyThaoGiang_DuGio" Member="DangKyThaoGiang" ThisKey="MaDK" OtherKey="MaDK" Type="DangKyThaoGiang" IsForeignKey="true" />
      <Association Name="GiangVien_DuGio" Member="GiangVien" ThisKey="GVDuGio" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiangVien" Member="GiangViens">
    <Type Name="GiangVien">
      <Column Name="MaGV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenGV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaCV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GoogleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="GiangVien_BienBan" Member="BienBans" ThisKey="MaGV" OtherKey="MaGV" Type="BienBan" />
      <Association Name="GiangVien_DangKyThaoGiang" Member="DangKyThaoGiangs" ThisKey="MaGV" OtherKey="MaGV" Type="DangKyThaoGiang" />
      <Association Name="GiangVien_DuGio" Member="DuGios" ThisKey="MaGV" OtherKey="GVDuGio" Type="DuGio" />
      <Association Name="ChucVu_GiangVien" Member="ChucVu" ThisKey="MaCV" OtherKey="MaCV" Type="ChucVu" IsForeignKey="true" />
      <Association Name="ChuongTrinh_GiangVien" Member="ChuongTrinh" ThisKey="MaCT" OtherKey="MaCT" Type="ChuongTrinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocKy" Member="HocKies">
    <Type Name="HocKy">
      <Column Name="MaHK" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHK" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Association Name="HocKy_DangKyThaoGiang" Member="DangKyThaoGiangs" ThisKey="MaHK" OtherKey="MaHK" Type="DangKyThaoGiang" />
    </Type>
  </Table>
  <Table Name="dbo.NamHoc" Member="NamHocs">
    <Type Name="NamHoc">
      <Column Name="MaNH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NamHoc_DangKyThaoGiang" Member="DangKyThaoGiangs" ThisKey="MaNH" OtherKey="MaNH" Type="DangKyThaoGiang" />
    </Type>
  </Table>
  <Table Name="dbo.NhanXet" Member="NhanXets">
    <Type Name="NhanXet">
      <Column Name="MaNX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhanXet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanXet_CTNhanXet" Member="CTNhanXets" ThisKey="MaNX" OtherKey="MaNX" Type="CTNhanXet" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuCham" Member="PhieuChams">
    <Type Name="PhieuCham">
      <Column Name="MaPhieuCham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDuGio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDanhGia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GVDanhGia" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="PhieuCham_CTDanhGia" Member="CTDanhGias" ThisKey="MaPhieuCham" OtherKey="MaPhieuCham" Type="CTDanhGia" />
      <Association Name="PhieuCham_CTNhanXet" Member="CTNhanXets" ThisKey="MaPhieuCham" OtherKey="MaPhieuCham" Type="CTNhanXet" />
      <Association Name="DuGio_PhieuCham" Member="DuGio" ThisKey="MaDuGio" OtherKey="MaDuGio" Type="DuGio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongBao" Member="ThongBaos">
    <Type Name="ThongBao">
      <Column Name="MaTB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ThongBao_CT_ThongBao" Member="CT_ThongBaos" ThisKey="MaTB" OtherKey="MaTB" Type="CT_ThongBao" />
      <Association Name="DangKyThaoGiang_ThongBao" Member="DangKyThaoGiang" ThisKey="MaDK" OtherKey="MaDK" Type="DangKyThaoGiang" IsForeignKey="true" />
    </Type>
  </Table>
</Database>